# Global Quarto configuration
# https://quarto.org/docs/projects/quarto-projects.html#project-metadata
# https://quarto.org/docs/reference/projects/options.html

project:
  output-dir: _output
  render:
    - guide.qmd

format:
  pdf:
    documentclass: article
    papersize: letter
    toc: true
    number-sections: true
    toc-depth: 5
    number-depth: 5
    code-fold: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    template-partials:
      - partials/before-body.tex
    header-includes:
      - \usepackage{./common/ohpc-doc}
  html:
    title-block-banner: true


# OpenHPC specific metadata that is applicable to all profiles 
ohpc:
  openhpc: OpenHPC
  revision: 3.x