title: "OpenHPC documentation for openEuler 22.03 LTS"

ohpc:
  openhpc: OpenHPC on openEuler 22.03
  baseOS: openEuler 22.03
  OSRepo: openEuler\_22.03
  OSTree: openEuler\_22.03
  OSTag: oe2203
  baseos: openeuler22.03
  baseosshort: openeuler22.03
