pdf:
  lang: zh

format:
  pdf:
    documentclass: ctexart
    toc-title: 内容

ohpc:
  content:
    introduction:
      title: 介绍
      contents: |
        <p>本指南介绍了使用组件的简单集群安装过程
         来自 {{<meta ohpc.openhpc >}} 软件堆栈。 {{<meta ohpc.openhpc>}}
         表示数字的聚合
         部署和管理 HPC Linux* 集群所需的常见要素
         包括配置工具、资源管理、I/O 客户端、开发
         工具和各种科学图书馆。 这些包已被
         预先构建时考虑了 HPC 集成，同时符合常见的 \Linux{}
         分配标准。</p>

         <p>此处的文档旨在
         相当通用，但使用小型 4 节点的潜在动机
         \iftoggleverb{isxCATstateful} 有状态 \else 无状态 \fi
         集群安装定义了一个逐步的过程。 一些
         包括可选的定制，目的是这些集体
         可以根据本地站点自定义的需要修改说明。</p>
      base_edition: |
        **基础 Linux 版本**：本版指南的重点内容
         无需使用配套配置管理系统即可安装
         直接使用发行版提供的组件包管理工具
         选择。 接下来的步骤还突出显示了系统的具体更改
         集群安装过程中所需的配置文件
         过程。
      audience:
        title: 目标听众
        paragraph1: |
          本指南面向经验丰富的 HPC \Linux{} 系统管理员
           环境。 了解软件包管理、系统网络和
           假定采用 PXE 引导。 命令行输入示例在全文中突出显示
           本指南通过以下语法：
        paragraph2: |
          除非另有说明，所提供的示例均以
           提升（root）权限。 这些示例还假设使用 BASH 登录
           shell，尽管可以替换其他 shell 中的等效命令。
           除了本指南中提到的特定命令行指令外，
           替代约定用于突出显示潜在有用的提示或可选的
           配置选项。 这些提示通过以下格式突出显示：
        tip1: |
          生活是一个白痴讲述的故事，充满了毫无意义的喧嚣和愤怒。 ——威利·谢克斯
      requirements:
        title: 要求/假设
        paragraph1: |
          此安装方案假设单个头节点可用
           *主*和四个*计算*节点。 *主*节点充当
           整体系统管理服务器 (SMS)，并配备了 {{<meta ohpc.baseOS >}}，并且是
           随后配置为提供剩余的*计算*节点
           {{<meta ohpc.provisioner >}} 在
           \iftoggleverb{isxCATstateful} 有状态 \else 无状态 \fi
           配置。 术语 *master* 和 SMS 是
           在本指南中可互换使用。 对于电源管理，我们假设
           计算节点基板管理控制器 (BMC) 可通过 IPMI 使用
           来自所选的主控主机。 对于文件系统，我们假设所选的主系统
           服务器将托管一个可供计算使用的 {{< meta ohpc.NFS >}} 文件系统
           节点。
        paragraph1-x86_64: |
          还讨论了安装信息以选择性地安装
           并行文件系统，在这种情况下，并行文件系统被假定为
           先前存在。
        paragraph1-figure-caption: |
          物理集群架构概述。
        paragraph2: |
          所讨论的物理架构的概要如图所示
           图~\ref{fig:physical_arch} 并突出显示了高级网络
           配置。 *主*主机需要至少两个以太网接口
           *eth0* 连接到本地数据中心网络并使用 *eth1*
           配置和管理集群后端（请注意，这些接口名称
           是示例，可能会有所不同，具体取决于本地设置和操作系统
           惯例）。 每个计算节点预计有两个逻辑 IP 接口：
           第一个是标准以太网接口，用于配置和
           资源管理。 第二个用于连接到每个主机的 BMC，是
           用于电源管理和远程控制台访问。 物理连接
           这两个逻辑 IP 网络通常通过单独的布线来容纳
           交换基础设施； 然而，也可以采用替代配置
           通过使用共享 NIC 来容纳，该 NIC 运行数据包过滤器来转移
           主机和BMC之间的管理数据包。
        paragraph2-x86_64: |
          除了IP网络外，还有一个可选的高速网络
           （本节中的 {{< meta ohpc.InfiniBand >}} 或 {{< meta ohpc.OmniPath >}}）也连接到每个
           主机。 该高速网络用于应用程序消息传递和
           也可选择并行文件系统连接（例如
           现有的 {{< meta ohpc.Lustre >}} 或 BeeGFS 存储目标）。
      inputs:
        title: 输入
        paragraph1: |
          由于本秘籍详细介绍了从裸机开始安装集群，因此需要定义 IP 地址和
           收集硬件 MAC 地址以支持受控的配置过程。 这些值必然是唯一的
           到正在使用的硬件，并且本文档在命令行中使用变量替换 **$\{variable\}**
           下面的示例强调了需要本地站点输入的地方。 必需和可选变量的摘要
           整个食谱中使用的内容如下所示。 请注意，虽然上面的示例定义对应于一个小的
           4节点计算子系统，计算参数以数组格式定义，以适应更大的逻辑扩展
           节点数。
    bos:
      title: 安装基础操作系统 (BOS)
      paragraph1: |
        <p>在外部设置中，将所需的 BOS 安装在
         *主* SMS 主机通常涉及从新的 DVD ISO 映像启动
         服务器。 通过这种方法，插入 {{< meta ohpc.baseOS >}} DVD，重新启动主机，然后
         按照发行版提供的说明在您选择的 {*master*} 主机上安装 BOS。
         或者，如果选择使用预装服务器，请
         验证它是否配备了所需的 {{< meta ohpc.baseOS >}} 发行版。</p>

         <p>在开始安装 {{<meta ohpc.OHPC >}} 组件之前，需要几个额外的组件
         此处记录了 SMS 主机配置的注意事项。 第一的，
         本文的安装方法假设
         SMS 主机名可在本地解析。 取决于你采取的方式
         安装了 BOS，可能已经定义了足够的条目
         在 **/etc/hosts** 中。 如果不是，可以使用以下添加来识别
         您的短信主机。</p>
      paragraph2: |
        <p>虽然理论上可以在配置的集群上启用 SELinux
         与 {{<meta ohpc.provisioner >}}，
         这样做超出了本文档的范围。 甚至使用
         宽容模式可能会出现问题，因此我们建议在
         *主*短信主机。 如果SELinux组件安装在本地，
         *selinuxenabled* 命令可用于确定 SELinux 是否已启用
         目前已启用。 如果启用，请参阅发行版文档以获取信息
         关于如何禁用。</p>

         <p>最后，配置服务依赖于 DHCP、TFTP 和 HTTP 网络协议。
         根据 SMS 主机上的本地 BOS 配置，默认防火墙
         规则可能禁止这些服务。 因此，这个食谱假设本地
         SMS 主机上运行的防火墙被禁用。 如果安装了，默认
         可以按如下方式禁用防火墙服务：</p>

  title:
    clusterBuildingRecipes: 集群建设秘诀
    baseOsSuffix: 基础操作系统
    editionForLinux: Linux 版本*