name: Run recipe

on:
  push:
    branches:
      - 3.x
      - run-recipe-on-gha
  # pull_request:
  #   branches:
  #     - 3.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true      

jobs:
  openEuler:
    runs-on: 'self-hosted'
    name: Run recipe on openEuler
    # container:
    #   image: docker.io/openeuler/openeuler:22.03-lts
    steps:
    - uses: actions/checkout@v3
    - name: Run recipe
      run: |
        set -xe
        . /etc/profile.d/lmod.sh
        sudo tests/ci/run_build.py ohpc components/admin/docs/SPECS/docs.spec
        sudo dnf -y install $(find /home/ohpc/rpmbuild/RPMS/ -name "*rpm") || true
        cp docs/recipes/install/openeuler22.03/input.local.template input.local
        export OHPC_INPUT_LOCAL=./docs/recipes/install/openeuler22.03/input.local.tests
        sudo bash /opt/ohpc/pub/doc/recipes/openeuler22.03/aarch64/warewulf/slurm/recipe.sh
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: recipe.sh
        path: |
          /opt/ohpc/pub/doc/recipes/openeuler22.03/aarch64/warewulf/slurm/recipe.sh
  
