name: Validate

on: [pull_request]

jobs:
  check_spec:

    runs-on: ubuntu-latest
    container:
      image: docker.io/library/rockylinux:8

    steps:
    - name: Setup
      run: |
        dnf install -y epel-release git python3
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Changes
      run: |
        tests/ci/check_spec.py ${{ steps.files.outputs.added_modified }}


  build_on_rhel:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/rockylinux:8
    steps:
    - name: Setup
      run: |
        dnf install -y epel-release dnf-plugins-core git python3 make http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm findutils rpm-build wget gawk
        dnf config-manager --set-enabled powertools
        dnf config-manager --set-enabled devel
        wget http://obs.openhpc.community:82/OpenHPC:/2.6:/Factory/EL_8/OpenHPC:2.6:Factory.repo -O /etc/yum.repos.d/obs.repo
        dnf install -y lmod-ohpc
        adduser ohpc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}

  build_on_leap:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/leap:15.3
    steps:
    - name: Setup
      run: |
        zypper -n install awk rpmbuild wget python3 make
        zypper -n --no-gpg-checks install http://repos.openhpc.community/OpenHPC/2/Leap_15/x86_64/ohpc-release-2-1.leap15.x86_64.rpm
        wget http://obs.openhpc.community:82/OpenHPC:/2.6:/Factory/Leap_15/OpenHPC:2.6:Factory.repo -O /etc/zypp/repos.d/obs.repo
        zypper -n --no-gpg-checks install lmod-ohpc
        useradd -m ohpc

  build_on_openEuler:
    runs-on: ubuntu-latest
    container:
      image: docker.io/openeuler/openeuler:22.03-lts
    steps:
    - name: Setup
      run: |
        dnf install -y http://121.36.3.168:82/home:/huangtianhua:/ohpc/standard_x86_64/x86_64/ohpc-release-2-1.oe2203.ohpc.2.0.0.x86_64.rpm openEuler-release dnf-plugins-core git python3 make findutils rpm-build wget gawk
        yum install -y lmod-ohpc
        adduser ohpc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: Validate Build
      run: |
        . /etc/profile.d/lmod.sh
        tests/ci/run_build.py ohpc ${{ steps.files.outputs.added_modified }}
